### ISSUE TITLE
Uncaught Exception on missing directory

### ISSUE THREAD

**Issue by rossriley** [bolt/filesystem#36]
On a clean composer install, bolt/filesystem current dev-master.

After install and navigating to either `/` or `/bolt` the following fatal error occurs

```
Fatal error: Uncaught exception 'Bolt\Filesystem\Exception\DirectoryCreationException' with message 
'Failed to create directory: <snip>/public/thumbs' in <snip>/vendor/bolt/filesystem/src/Adapter/Local.php:25
```

**Comment by CarsonF** [comment]
This sounds like a permissions problem. That is the expected behavior IMO.
